spring.application.name=springboot-events
server.port=9093
spring.datasource.url=jdbc:postgresql://localhost:5432/events?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=sowmya@123

#Hibernate Property
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
